/**
 * Development seed data (mirrors database/seeds/*.sql).
 * Realistic creators and content — no lorem ipsum, no "Test User".
 */
import type {
  BuzzNotification,
  Creator,
  LongVideo,
  NewsArticle,
  Post,
  ShortVideo,
  Story,
  TrendingTopic,
} from "../domain/types";

const V = (name: string) => `https://storage.googleapis.com/gtv-videos-bucket/sample/${name}.mp4`;

export const CURRENT_USER_ID = "u-alex";

export const creators: Creator[] = [
  {
    id: "u-alex",
    username: "you",
    displayName: "Alex Rivera",
    avatarKey: "avatar/alex-rivera",
    verified: true,
    bio: "Building things - Coffee & code - BUZZ early adopter",
    followers: 1300,
    following: 342,
    posts: 6,
  },
  {
    id: "u-maya",
    username: "maya.k",
    displayName: "Maya Kapoor",
    avatarKey: "avatar/maya-kapoor",
    verified: true,
    bio: "Natural light portraits. Mumbai to Lisbon.",
    followers: 84200,
    following: 412,
    posts: 318,
  },
  {
    id: "u-leo",
    username: "leo.wilder",
    displayName: "Leo Wilder",
    avatarKey: "avatar/leo-wilder",
    verified: false,
    bio: "Roads, ridges and long exposures.",
    followers: 22800,
    following: 190,
    posts: 204,
  },
  {
    id: "u-nina",
    username: "nina.co",
    displayName: "Nina Cortez",
    avatarKey: "avatar/nina-cortez",
    verified: true,
    bio: "Product designer. Interfaces that breathe.",
    followers: 51600,
    following: 288,
    posts: 142,
  },
  {
    id: "u-sam",
    username: "sam_films",
    displayName: "Sam Okafor",
    avatarKey: "avatar/sam-okafor",
    verified: false,
    bio: "Short films, mostly at night.",
    followers: 17400,
    following: 233,
    posts: 96,
  },
  {
    id: "u-riko",
    username: "riko",
    displayName: "Riko Tanaka",
    avatarKey: "avatar/riko-tanaka",
    verified: true,
    bio: "Neon Rain. Producer, Tokyo.",
    followers: 132000,
    following: 154,
    posts: 271,
  },
  {
    id: "u-june",
    username: "june.h",
    displayName: "June Hart",
    avatarKey: "avatar/june-hart",
    verified: false,
    bio: "Kitchen experiments in 60 seconds.",
    followers: 64300,
    following: 320,
    posts: 415,
  },
];

const now = Date.UTC(2026, 7, 27, 12, 0, 0);
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();

export const stories: Story[] = [
  ["u-maya", "story/maya-golden", 12, false],
  ["u-leo", "story/leo-ridge", 48, false],
  ["u-nina", "story/nina-studio", 96, true],
  ["u-sam", "story/sam-set", 140, false],
  ["u-riko", "story/riko-booth", 220, true],
  ["u-june", "story/june-market", 300, true],
].map(([authorId, key, mins, viewed]) => ({
  id: `st-${key as string}`,
  authorId: authorId as string,
  media: {
    kind: "image" as const,
    objectKey: key as string,
    width: 1080,
    height: 1920,
    blurColor: "oklch(0.7 0.05 295)",
    alt: "Story",
  },
  createdAt: minutesAgo(mins as number),
  viewed: viewed as boolean,
}));

export const trending: TrendingTopic[] = [
  {
    id: "t-buzz",
    label: "#buzz",
    kind: "hashtag",
    category: "Trending",
    postCount: 128000,
    velocity: 0.94,
    region: "global",
  },
  {
    id: "t-golden",
    label: "#goldenhour",
    kind: "hashtag",
    category: "Travel",
    postCount: 61400,
    velocity: 0.81,
    region: "global",
  },
  {
    id: "t-neon",
    label: "#neonrain",
    kind: "hashtag",
    category: "Music",
    postCount: 31700,
    velocity: 0.88,
    region: "global",
  },
  {
    id: "t-indie",
    label: "#indiefilm",
    kind: "hashtag",
    category: "Entertainment",
    postCount: 24900,
    velocity: 0.66,
    region: "global",
  },
  {
    id: "t-design",
    label: "#designdaily",
    kind: "hashtag",
    category: "Technology",
    postCount: 8800,
    velocity: 0.72,
    region: "global",
  },
  {
    id: "t-ondevice",
    label: "On-device AI",
    kind: "topic",
    category: "Technology",
    postCount: 48200,
    velocity: 0.91,
    region: "global",
  },
  {
    id: "t-creator",
    label: "Creator Economy",
    kind: "topic",
    category: "Business",
    postCount: 22400,
    velocity: 0.58,
    region: "global",
  },
  {
    id: "t-sundance",
    label: "Sundance 2026",
    kind: "event",
    category: "Entertainment",
    postCount: 18800,
    velocity: 0.63,
    region: "us",
  },
  {
    id: "t-overtime",
    label: "Overtime Thriller",
    kind: "event",
    category: "Sports",
    postCount: 12100,
    velocity: 0.97,
    region: "us",
  },
  {
    id: "t-lisbon",
    label: "Lisbon",
    kind: "location",
    category: "Travel",
    postCount: 9400,
    velocity: 0.44,
    region: "eu",
  },
];

interface SeedPost {
  id: string;
  authorId: string;
  caption: string;
  key: string;
  aspect: number;
  hashtags: string[];
  category: string;
  location?: string;
  minutes: number;
  metrics: [number, number, number, number, number];
}

const seedPosts: SeedPost[] = [
  {
    id: "p-1",
    authorId: "u-maya",
    caption: "Golden hour never disappoints. #photography",
    key: "photo/sand-hands",
    aspect: 1,
    hashtags: ["photography", "goldenhour"],
    category: "Travel",
    location: "Praia da Ursa, Portugal",
    minutes: 12,
    metrics: [2140, 87, 24, 310, 41200],
  },
  {
    id: "p-2",
    authorId: "u-nina",
    caption: "Sketching a new home screen. Purple looks good on everything.",
    key: "photo/green-rails",
    aspect: 0.9,
    hashtags: ["designdaily", "product"],
    category: "Technology",
    minutes: 60,
    metrics: [987, 64, 12, 143, 18800],
  },
  {
    id: "p-3",
    authorId: "u-sam",
    caption: "Behind the scenes on the short film. Wrapped day 3.",
    key: "photo/underwater",
    aspect: 0.85,
    hashtags: ["indiefilm", "bts"],
    category: "Entertainment",
    location: "Lagos, Nigeria",
    minutes: 1440,
    metrics: [812, 51, 9, 96, 12400],
  },
  {
    id: "p-4",
    authorId: "u-leo",
    caption: "Six hours of switchbacks for ninety seconds of light.",
    key: "photo/cliff-road",
    aspect: 0.75,
    hashtags: ["goldenhour", "travel"],
    category: "Travel",
    location: "Vestrahorn, Iceland",
    minutes: 220,
    metrics: [3410, 122, 58, 640, 72100],
  },
  {
    id: "p-5",
    authorId: "u-june",
    caption: "Market haul. Three ingredients, one pan, twelve minutes.",
    key: "photo/market-produce",
    aspect: 1,
    hashtags: ["food", "cooking"],
    category: "Food",
    minutes: 420,
    metrics: [1560, 210, 33, 401, 29800],
  },
  {
    id: "p-6",
    authorId: "u-riko",
    caption: "Studio rebuild finished. Everything routes through the desk now.",
    key: "photo/studio-desk",
    aspect: 1.2,
    hashtags: ["neonrain", "music"],
    category: "Music",
    location: "Shibuya, Tokyo",
    minutes: 90,
    metrics: [5210, 318, 140, 980, 118000],
  },
];

export const posts: Post[] = seedPosts.map((p) => ({
  id: p.id,
  authorId: p.authorId,
  source: "buzz",
  caption: p.caption,
  media: [
    {
      kind: "image",
      objectKey: p.key,
      width: 1200,
      height: Math.round(1200 / p.aspect),
      blurColor: "oklch(0.85 0.02 285)",
      alt: p.caption,
    },
  ],
  hashtags: p.hashtags,
  ...(p.location ? { location: p.location } : {}),
  category: p.category,
  metrics: {
    likes: p.metrics[0],
    comments: p.metrics[1],
    shares: p.metrics[2],
    saves: p.metrics[3],
    views: p.metrics[4],
  },
  createdAt: minutesAgo(p.minutes),
  visibility: "public",
  moderationStatus: "approved",
}));

/** Content mirrored in from external platforms through the integration layer. */
export const externalPosts: Post[] = [
  {
    id: "x-1",
    authorId: "u-nina",
    source: "x",
    sourceName: "X",
    externalUrl: "https://x.com/ninacortez/status/1",
    caption:
      "Shipped the new discovery grid today. Masonry with mixed aspect ratios reads far better than a uniform grid — the eye actually has somewhere to travel.",
    media: [
      {
        kind: "image",
        objectKey: "photo/grid-preview",
        width: 1200,
        height: 675,
        blurColor: "oklch(0.8 0.03 295)",
        alt: "Discovery grid preview",
      },
    ],
    hashtags: ["designdaily"],
    category: "Technology",
    metrics: { likes: 4120, comments: 231, shares: 512, saves: 380, views: 210000 },
    createdAt: minutesAgo(180),
    visibility: "public",
    moderationStatus: "approved",
  },
  {
    id: "x-2",
    authorId: "u-riko",
    source: "x",
    sourceName: "X",
    externalUrl: "https://x.com/riko/status/2",
    caption: "New track drops Friday. Small preview lives in Shorts.",
    media: [],
    hashtags: ["neonrain"],
    category: "Music",
    metrics: { likes: 9800, comments: 604, shares: 1200, saves: 740, views: 480000 },
    createdAt: minutesAgo(320),
    visibility: "public",
    moderationStatus: "approved",
  },
];

export const news: NewsArticle[] = [
  {
    id: "n-1",
    title: "The quiet rise of small-team social apps in 2026",
    subheadline:
      "Lean teams are shipping discovery products that once needed hundreds of engineers.",
    summary:
      "Lean teams are shipping discovery products that once needed hundreds of engineers, and audiences are following them.",
    body: [
      "For most of the last decade, launching a social app meant raising a war chest first. Servers, ranking infrastructure, moderation tooling and mobile clients each demanded a dedicated team. That math has inverted: a dozen people with rented GPUs and open models can now ship a feed that feels alive on day one.",
      "The shift shows up in the numbers. Three of the ten fastest-growing social apps this year report teams under twenty people, and two of them run no datacenter of their own. Distribution moved to short video, hosting moved to the edge, and ranking moved closer to the handset.",
      "Skeptics note the graveyard is just as crowded as ever. Discovery is cheap; retention is not. The teams surviving past year two share one trait: they picked a single community and served it obsessively before chasing scale.",
    ],
    pullQuote:
      "Distribution moved to short video, hosting moved to the edge, and ranking moved closer to the handset.",
    sourceName: "The Verge",
    sourceHandle: "verge",
    reporter: "Amara Diallo",
    category: "Technology",
    url: "https://example.com/small-team-social",
    imageKey: "news/rain-window",
    imageCredit: "Illustration: Studio Nuru",
    publishedAt: minutesAgo(120),
    updatedAt: minutesAgo(18),
    live: true,
    location: "San Francisco",
    tags: ["startups", "social media", "ai"],
    readMinutes: 4,
    contentType: "analysis",
    updates: [
      {
        time: "21:32",
        text: "A fourth app crossed one million installs today, per store estimates.",
        source: "@verge",
      },
      {
        time: "21:17",
        text: "Two of the teams confirmed they run ranking fully on-device.",
        source: "@amara",
      },
      {
        time: "20:54",
        text: "Initial report: three of the ten fastest-growing social apps run teams under twenty.",
        source: "@verge",
      },
    ],
    coverage: [
      {
        name: "Wired",
        headline: "On-device models are changing how feeds get ranked",
        summary: "Ranking is moving closer to the handset, cutting latency and server cost.",
        time: "4h ago",
      },
      {
        name: "Business Daily",
        headline: "Creator payouts shift toward saves, not views",
        summary: "Platforms are rewarding intent signals over raw impressions.",
        time: "11h ago",
      },
    ],
  },
  {
    id: "n-2",
    title: "On-device models are changing how feeds get ranked",
    subheadline: "Ranking is moving closer to the handset, cutting latency and server cost.",
    summary: "Ranking is moving closer to the handset, cutting latency and server cost.",
    body: [
      "The heaviest part of a social feed used to live in a datacenter. Candidate generation, scoring and re-ranking happened thousands of kilometres from the thumb doing the scrolling. New on-device models collapse that round trip to milliseconds.",
      "Battery and thermal limits still cap model size, so the pattern emerging is hybrid: the server proposes a few hundred candidates, the phone does the final personal cut. Early adopters report ranking latency down by an order of magnitude.",
    ],
    sourceName: "Wired",
    sourceHandle: "wired",
    reporter: "Jonas Weber",
    category: "Technology",
    url: "https://example.com/on-device-ranking",
    imageKey: "news/chip-macro",
    imageCredit: "Photo: Circuit Archive",
    publishedAt: minutesAgo(240),
    updatedAt: minutesAgo(240),
    live: false,
    location: "Berlin",
    tags: ["ai", "mobile", "ranking"],
    readMinutes: 3,
    contentType: "reporting",
    updates: [],
    coverage: [
      {
        name: "The Verge",
        headline: "The quiet rise of small-team social apps in 2026",
        summary: "Lean teams ship discovery products that once needed hundreds of engineers.",
        time: "2h ago",
      },
    ],
  },
  {
    id: "n-3",
    title: "Overtime thriller sends the series to a decider",
    subheadline: "Two lead changes in the final ninety seconds set up a game seven.",
    summary: "Two lead changes in the final ninety seconds set up a game seven.",
    body: [
      "Nobody in the arena sat down for the last six minutes. Down four with ninety seconds left, the visitors ripped off back-to-back transition threes, forced the turnover, and stole a game that had been inked as a loss since halftime.",
      "The decider tips Sunday. Both coaches leaned on seven-man rotations, so expect tired legs and a tactical chess match from the opening tip.",
    ],
    sourceName: "Athletic Wire",
    sourceHandle: "athleticwire",
    reporter: "Pendo Massawe",
    category: "Sports",
    url: "https://example.com/overtime",
    imageKey: "news/arena-night",
    imageCredit: "Photo: Courtside Collective",
    publishedAt: minutesAgo(65),
    updatedAt: minutesAgo(9),
    live: true,
    location: "Dar es Salaam",
    tags: ["basketball", "finals", "tanzania"],
    readMinutes: 2,
    contentType: "breaking",
    updates: [
      {
        time: "21:41",
        text: "Final: 104–102. Game seven confirmed for Sunday evening.",
        source: "@athleticwire",
      },
      {
        time: "21:28",
        text: "Turnover with eleven seconds left — visitors ball, down one.",
        source: "@pendo",
      },
      {
        time: "21:15",
        text: "Back-to-back threes cut the lead to four. Arena is deafening.",
        source: "@athleticwire",
      },
    ],
    coverage: [
      {
        name: "Mwananchi",
        headline: "Dakika za lala salama zaipeleka fainali",
        summary: "Mabadiliko mawili ya uongozi katika sekunde tisini za mwisho.",
        time: "1h ago",
      },
      {
        name: "The Citizen",
        headline: "Series heads to decider after overtime classic",
        summary: "Coaches leaned on seven-man rotations throughout.",
        time: "2h ago",
      },
    ],
  },
  {
    id: "n-4",
    title: "Lisbon's night trains are booked solid through September",
    subheadline: "Slow travel demand keeps climbing across southern Europe.",
    summary: "Slow travel demand keeps climbing across southern Europe.",
    body: [
      "Every couchette out of Lisbon is spoken for until autumn. Operators blame a familiar cocktail: flight shame, remote work, and a generation that would rather wake up somewhere new than queue at an airport.",
      "Rail companies are responding with refurbished sleeper cars and dynamic pricing that regulars describe, diplomatically, as ambitious.",
    ],
    sourceName: "Continental",
    sourceHandle: "continental",
    reporter: "Ines Duarte",
    category: "Travel",
    url: "https://example.com/night-trains",
    imageKey: "news/night-train",
    imageCredit: "Photo: Rail Journal",
    publishedAt: minutesAgo(400),
    updatedAt: minutesAgo(400),
    live: false,
    location: "Lisbon",
    tags: ["travel", "trains", "europe"],
    readMinutes: 3,
    contentType: "reporting",
    updates: [],
    coverage: [],
  },
  {
    id: "n-5",
    title: "Restaurant groups bet on 12-seat rooms",
    subheadline: "Smaller dining rooms are outperforming flagship venues on margin.",
    summary: "Smaller dining rooms are outperforming flagship venues on margin.",
    body: [
      "The industry's new status symbol seats twelve. Groups report that tiny rooms turn tables faster, waste less, and — crucially — photograph better than echoing flagships.",
      "Chefs are split. Some call it the tasting-menu format finally finding its architecture; others see landlords chopping awkward basements into rent machines.",
    ],
    sourceName: "Service Weekly",
    sourceHandle: "serviceweekly",
    reporter: "Ruth Adler",
    category: "Lifestyle",
    url: "https://example.com/small-rooms",
    imageKey: "news/dining-room",
    imageCredit: "Photo: Service Weekly",
    publishedAt: minutesAgo(520),
    updatedAt: minutesAgo(520),
    live: false,
    location: "London",
    tags: ["food", "restaurants", "business"],
    readMinutes: 3,
    contentType: "analysis",
    updates: [],
    coverage: [],
  },
  {
    id: "n-6",
    title: "Creator payouts shift toward saves, not views",
    subheadline: "Platforms are rewarding intent signals over raw impressions.",
    summary: "Platforms are rewarding intent signals over raw impressions.",
    body: [
      "Views were always a vanity metric wearing a business suit. This quarter, three major platforms rewrote payout formulas around saves, shares and completions — the signals that predict a viewer will come back tomorrow.",
      "Early data favors slow-burn educational creators over viral clip farms. Expect formats to get longer, calmer, and considerably more useful.",
    ],
    pullQuote: "Views were always a vanity metric wearing a business suit.",
    sourceName: "Business Daily",
    sourceHandle: "businessdaily",
    reporter: "Kwame Osei",
    category: "Business",
    url: "https://example.com/creator-payouts",
    imageKey: "news/studio-lights",
    imageCredit: "Photo: Studio Archive",
    publishedAt: minutesAgo(700),
    updatedAt: minutesAgo(700),
    live: false,
    location: "Nairobi",
    tags: ["creators", "money", "platforms"],
    readMinutes: 4,
    contentType: "analysis",
    updates: [],
    coverage: [
      {
        name: "The Verge",
        headline: "The quiet rise of small-team social apps in 2026",
        summary: "Lean teams ship discovery products that once needed hundreds of engineers.",
        time: "2h ago",
      },
    ],
  },
  {
    id: "n-7",
    title: "Dar es Salaam BRT adds night corridor to Ubungo",
    subheadline: "Buses run until 1am on the new corridor starting Friday.",
    summary:
      "Buses run until 1am on the new Ubungo corridor starting Friday, with fares unchanged.",
    body: [
      "Commuters on the Ubungo corridor get their evenings back. From Friday, rapid buses run until 1am with ten-minute headways, and weekend service stretches to match.",
      "Transport officials say the night corridor is a six-month trial. Ridership numbers in November decide whether Temeke and Mbagala get the same treatment.",
      "Drivers' unions welcomed the move but asked for better-lit terminals, a request the agency says is already funded.",
    ],
    pullQuote:
      "Ridership numbers in November decide whether Temeke and Mbagala get the same treatment.",
    sourceName: "The Citizen",
    sourceHandle: "thecitizen",
    reporter: "John Doe",
    category: "Tanzania",
    url: "https://example.com/brt-night",
    imageKey: "news/night-train",
    imageCredit: "Photo: Citizen Media",
    publishedAt: minutesAgo(45),
    updatedAt: minutesAgo(5),
    live: true,
    location: "Dar es Salaam",
    tags: ["tanzania", "transport", "dar es salaam", "brt"],
    readMinutes: 2,
    contentType: "breaking",
    updates: [
      {
        time: "21:50",
        text: "Agency confirms first night buses roll Friday, fares unchanged.",
        source: "@thecitizen",
      },
      {
        time: "21:20",
        text: "Drivers' union welcomes the move, asks for better-lit terminals.",
        source: "@johndoe",
      },
      {
        time: "20:54",
        text: "Initial reports: Ubungo corridor gets night service on a six-month trial.",
        source: "@thecitizen",
      },
    ],
    coverage: [
      {
        name: "Mwananchi",
        headline: "Mabasi ya usiku kuanza Ubungo Ijumaa",
        summary: "Nauli hazitabadilika, mabasi kila dakika kumi.",
        time: "40min ago",
      },
      {
        name: "Al Jazeera",
        headline: "Dar es Salaam expands night transit",
        summary: "East African cities race to serve night economies.",
        time: "2h ago",
      },
    ],
  },
  {
    id: "n-8",
    title: "Taifa Stars name squad for AFCON qualifiers",
    subheadline: "Three uncapped teenagers make the 26-man list.",
    summary: "Three uncapped teenagers make the 26-man squad for next month's AFCON qualifiers.",
    body: [
      "The head coach rolled the dice: three teenagers with a combined eleven senior appearances headline a squad short on its usual European-based core.",
      "Qualification math is simple — four points from two home games all but seals it. The new faces train with the full squad from Monday.",
    ],
    sourceName: "Mwananchi",
    sourceHandle: "mwananchi",
    reporter: "Asha Juma",
    category: "Sports",
    url: "https://example.com/taifa-squad",
    imageKey: "news/arena-night",
    imageCredit: "Photo: Mwananchi Sport",
    publishedAt: minutesAgo(180),
    updatedAt: minutesAgo(180),
    live: false,
    location: "Dar es Salaam",
    tags: ["football", "afcon", "tanzania", "taifa stars"],
    readMinutes: 2,
    contentType: "reporting",
    updates: [],
    coverage: [
      {
        name: "The Citizen",
        headline: "Youth gets its chance in Stars squad",
        summary: "Coach bets on domestic league form.",
        time: "3h ago",
      },
    ],
  },
  {
    id: "n-9",
    title: "What the new mobile-money fees actually cost you",
    subheadline: "A line-by-line breakdown of sending, withdrawing and saving.",
    summary: "A line-by-line breakdown of what sending, withdrawing and saving really cost.",
    body: [
      "Fee schedules are designed to be skimmed, not understood. We ran the most common transactions — sending 50,000, withdrawing 200,000, and parking savings for a month — across the three big wallets.",
      "The headline: withdrawing remains the tax nobody budgets for, while bank-to-wallet rails quietly became the cheapest way to move money.",
      "Our takeaway table: batch your withdrawals, send off-peak where pricing tiers allow, and let savings sit — most wallets now beat mattress rates by a mile.",
    ],
    sourceName: "Business Daily",
    sourceHandle: "businessdaily",
    reporter: "Kwame Osei",
    category: "Business",
    url: "https://example.com/momo-fees",
    imageKey: "news/studio-lights",
    imageCredit: "Illustration: Ledger Studio",
    publishedAt: minutesAgo(300),
    updatedAt: minutesAgo(300),
    live: false,
    location: "Dar es Salaam",
    tags: ["money", "m-pesa", "tanzania", "fintech"],
    readMinutes: 5,
    contentType: "analysis",
    updates: [],
    coverage: [],
  },
  {
    id: "n-10",
    title: "Africa's startup funding finds its floor",
    subheadline: "Fintech takes half the cheques as investors return to fundamentals.",
    summary:
      "Fintech takes half the cheques as investors return to fundamentals across the continent.",
    body: [
      "After two years of shrinking rounds, African startup funding has stopped falling. Quarterly totals held flat, and — more tellingly — the number of funded startups actually grew.",
      "Fintech still takes roughly half of every dollar, but climate tech and logistics posted their best quarters on record. Lagos, Nairobi and Cairo split the spoils; Dar es Salaam's pipeline doubled from a small base.",
      "Founders describe a market that rewards revenue over narratives. 'Nobody asks about your waitlist anymore,' one CEO laughed. 'They ask about last month.'",
    ],
    pullQuote: "Nobody asks about your waitlist anymore. They ask about last month.",
    sourceName: "Continental",
    sourceHandle: "continental",
    reporter: "Zawadi Kimaro",
    category: "Africa",
    url: "https://example.com/africa-funding",
    imageKey: "news/dining-room",
    imageCredit: "Photo: Continental File",
    publishedAt: minutesAgo(600),
    updatedAt: minutesAgo(600),
    live: false,
    location: "Lagos",
    tags: ["africa", "startups", "fintech", "funding"],
    readMinutes: 4,
    contentType: "analysis",
    updates: [],
    coverage: [
      {
        name: "Al Jazeera",
        headline: "African tech weathers the downturn",
        summary: "Investors return to fundamentals.",
        time: "9h ago",
      },
    ],
  },
];

const shortSeed: Array<[string, string, string, string, string, string, number]> = [
  ["s-1", "u-riko", "New beat. Loop it.", "Riko — Neon Rain", "Music", V("ForBiggerBlazes"), 21400],
  [
    "s-2",
    "u-june",
    "60-second pasta. Actually works.",
    "Kitchen loop 12",
    "Food",
    V("ForBiggerFun"),
    18200,
  ],
  [
    "s-3",
    "u-leo",
    "Ring road, hour nineteen.",
    "Ambient drive",
    "Travel",
    V("ForBiggerJoyrides"),
    15600,
  ],
  [
    "s-4",
    "u-nina",
    "Prototyping the create sheet.",
    "Studio hum",
    "Tech",
    V("ForBiggerEscapes"),
    9800,
  ],
  [
    "s-5",
    "u-maya",
    "One light, one reflector.",
    "Soft keys",
    "For You",
    V("ForBiggerMeltdowns"),
    12300,
  ],
];

export const shorts: ShortVideo[] = shortSeed.map(
  ([id, authorId, caption, soundtrack, category, url, likes]) => ({
    id,
    authorId,
    caption,
    soundtrack,
    category,
    video: {
      kind: "video",
      objectKey: url,
      posterKey: `short/${id}`,
      durationSeconds: 24,
      width: 1080,
      height: 1920,
      alt: caption,
    },
    metrics: { likes, comments: 812, shares: 340, saves: 260, views: likes * 12 },
  }),
);

interface VideoSeed {
  id: string;
  authorId: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  url: string;
  views: number;
  publishedAt: string;
  progress?: number;
}

const videoSeed: VideoSeed[] = [
  {
    id: "v-1",
    authorId: "u-riko",
    title: "Making Neon Rain — full studio walkthrough",
    description:
      "Every layer of Neon Rain broken down: the drum bus, the sidechained pads, and the vocal chain I use on every chorus. Timestamps in the pinned comment.",
    category: "Music",
    tags: ["studio", "beatmaking", "tutorial", "neon rain"],
    url: V("ForBiggerBlazes"),
    views: 212000,
    publishedAt: "1 week ago",
    progress: 620,
  },
  {
    id: "v-2",
    authorId: "u-leo",
    title: "Iceland ring road in 8 minutes",
    description:
      "Seven days, 1,300 kilometres, one very tired van. Waterfalls, black beaches and the hot spring we almost skipped — route map linked below.",
    category: "Travel",
    tags: ["iceland", "roadtrip", "travel guide", "vanlife"],
    url: V("ForBiggerJoyrides"),
    views: 1200000,
    publishedAt: "3 weeks ago",
    progress: 180,
  },
  {
    id: "v-3",
    authorId: "u-june",
    title: "The only knife skills tutorial you need",
    description:
      "Grip, claw, and the three cuts that cover 90% of home cooking. Practice along in real time — pause whenever you need, no rush.",
    category: "Food",
    tags: ["cooking", "knife skills", "tutorial", "kitchen basics"],
    url: V("ForBiggerFun"),
    views: 540000,
    publishedAt: "1 month ago",
  },
  {
    id: "v-4",
    authorId: "u-nina",
    title: "Design system tour — building BUZZ",
    description:
      "A walkthrough of the BUZZ interface kit: tokens, the purple accent rules, sheet motion, and how we keep every screen feeling like one product.",
    category: "Tech",
    tags: ["design system", "ui design", "tutorial", "buzz"],
    url: V("ForBiggerEscapes"),
    views: 38000,
    publishedAt: "4 days ago",
  },
  {
    id: "v-5",
    authorId: "u-maya",
    title: "Portrait lighting on a budget",
    description:
      "One window, one ₦5,000 reflector, zero excuses. Three setups from soft beauty light to dramatic evening portraits you can copy today.",
    category: "For You",
    tags: ["photography", "portrait", "lighting", "budget"],
    url: V("ForBiggerMeltdowns"),
    views: 96000,
    publishedAt: "5 days ago",
  },
];

export const videos: LongVideo[] = videoSeed.map((s) => ({
  id: s.id,
  authorId: s.authorId,
  title: s.title,
  description: s.description,
  category: s.category,
  tags: s.tags,
  video: {
    kind: "video",
    objectKey: s.url,
    posterKey: `video/${s.id}`,
    durationSeconds: 1330,
    width: 1920,
    height: 1080,
    alt: s.title,
  },
  views: s.views,
  publishedAt: s.publishedAt,
  ...(s.progress ? { progressSeconds: s.progress } : {}),
}));

/** Explore grid: mixed aspect ratios so the masonry has visual rhythm. */
export const explorePhotos = [
  { id: "e-1", key: "photo/cliff-road", aspect: 0.72, authorId: "u-leo", category: "Travel" },
  {
    id: "e-2",
    key: "photo/mushroom-light",
    aspect: 1.05,
    authorId: "u-maya",
    category: "Trending",
  },
  { id: "e-3", key: "photo/underwater", aspect: 0.86, authorId: "u-sam", category: "Trending" },
  { id: "e-4", key: "photo/blue-room", aspect: 1.35, authorId: "u-nina", category: "Technology" },
  { id: "e-5", key: "photo/paint-water", aspect: 1.2, authorId: "u-nina", category: "Latest" },
  { id: "e-6", key: "photo/ocean-sun", aspect: 0.78, authorId: "u-leo", category: "Travel" },
  { id: "e-7", key: "photo/dining-room", aspect: 1.3, authorId: "u-june", category: "Food" },
  { id: "e-8", key: "photo/desert-dunes", aspect: 1.25, authorId: "u-maya", category: "Travel" },
  { id: "e-9", key: "photo/bridge-cables", aspect: 0.8, authorId: "u-leo", category: "Latest" },
  { id: "e-10", key: "photo/studio-desk", aspect: 1.1, authorId: "u-riko", category: "Technology" },
  { id: "e-11", key: "photo/green-rails", aspect: 0.82, authorId: "u-nina", category: "Trending" },
  { id: "e-12", key: "photo/stadium-lights", aspect: 1.4, authorId: "u-sam", category: "Sports" },
  { id: "e-13", key: "photo/market-produce", aspect: 0.95, authorId: "u-june", category: "Food" },
  { id: "e-14", key: "photo/sand-hands", aspect: 1, authorId: "u-maya", category: "Latest" },
  { id: "e-15", key: "photo/night-train", aspect: 0.7, authorId: "u-leo", category: "Travel" },
  { id: "e-16", key: "photo/arena-crowd", aspect: 1.5, authorId: "u-sam", category: "Sports" },
];

export const notifications: BuzzNotification[] = [
  {
    id: "nt-1",
    kind: "like",
    actorId: "u-maya",
    body: 'liked your post "Late shift edits"',
    createdAt: minutesAgo(8),
    read: false,
  },
  {
    id: "nt-2",
    kind: "follow",
    actorId: "u-riko",
    body: "started following you",
    createdAt: minutesAgo(52),
    read: false,
  },
  {
    id: "nt-3",
    kind: "comment",
    actorId: "u-nina",
    body: "commented: this grid spacing is right",
    createdAt: minutesAgo(140),
    read: true,
  },
  {
    id: "nt-4",
    kind: "trending",
    actorId: "u-leo",
    body: "#goldenhour is trending in Travel",
    createdAt: minutesAgo(300),
    read: true,
  },
];
