/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'
import { Route as UUsernameIndexRouteImport } from './routes/u.$username.index'
import { Route as UUsernameFollowersRouteImport } from './routes/u.$username.followers'
import { Route as UUsernameFollowingRouteImport } from './routes/u.$username.following'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => VideosRoute,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameFollowersRoute = UUsernameFollowersRouteImport.update({
  id: '/u/$username/followers',
  path: '/u/$username/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameFollowingRoute = UUsernameFollowingRouteImport.update({
  id: '/u/$username/following',
  path: '/u/$username/following',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/shorts': typeof ShortsRoute
  '/videos': typeof VideosRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/shorts': typeof ShortsRoute
  '/videos': typeof VideosRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/u/$username': typeof UUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/shorts': typeof ShortsRoute
  '/videos': typeof VideosRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/u/$username/followers': typeof UUsernameFollowersRoute
  '/u/$username/following': typeof UUsernameFollowingRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/news'
    | '/profile'
    | '/shorts'
    | '/videos'
    | '/welcome'
    | '/videos/$videoId'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/news'
    | '/profile'
    | '/shorts'
    | '/videos'
    | '/welcome'
    | '/videos/$videoId'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/news'
    | '/profile'
    | '/shorts'
    | '/videos'
    | '/welcome'
    | '/videos/$videoId'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  ShortsRoute: typeof ShortsRoute
  VideosRoute: typeof VideosRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  UUsernameFollowersRoute: typeof UUsernameFollowersRoute
  UUsernameFollowingRoute: typeof UUsernameFollowingRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/followers': {
      id: '/u/$username/followers'
      path: '/u/$username/followers'
      fullPath: '/u/$username/followers'
      preLoaderRoute: typeof UUsernameFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/following': {
      id: '/u/$username/following'
      path: '/u/$username/following'
      fullPath: '/u/$username/following'
      preLoaderRoute: typeof UUsernameFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VideosRouteChildren {
  VideosVideoIdRoute: typeof VideosVideoIdRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosVideoIdRoute: VideosVideoIdRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  ShortsRoute: ShortsRoute,
  VideosRoute: VideosRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  UUsernameFollowersRoute: UUsernameFollowersRoute,
  UUsernameFollowingRoute: UUsernameFollowingRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
